export enum HotspotEvents {
  ADD_GATEWAY_INITIATED = 'AddGateway Initiated',
  ADD_GATEWAY_SUBMITTED = 'AddGateway Submitted',
  ASSERT_LOCATION_INITIATED = 'AssertLocation Initiated',
  ASSERT_LOCATION_SUBMITTED = 'AssertLocation Submitted',
  DEVICE_TRANSFER_INITIATED = 'DeviceTransfer Initiated',
  DEVICE_TRANSFER_SUBMITTED = 'DeviceTransfer Submitted',
  BLUETOOTH_SCAN_STARTED = 'Bluetooth Scan Started',
  BLUETOOTH_SCAN_FINISHED = 'Bluetooth Scan Finished',
  BLUETOOTH_CONNECTION_STARTED = 'Bluetooth Connection Started',
  BLUETOOTH_CONNECTION_SUCCEED = 'Bluetooth Connection Succeed',
  BLUETOOTH_CONNECTION_FAILED = 'Bluetooth Connection Failed',
  WIFI_SCAN_STARTED = 'Wifi Scan Started',
  WIFI_SCAN_FINISHED = 'Wifi Scan Finished',
}
