export enum HotspotEvents {
  ADD_GATEWAY_STARTED = 'add_gateway_started',
  ADD_GATEWAY_SUBMITTED = 'add_gateway_submitted',
  ASSERT_LOCATION_STARTED = 'assert_location_started',
  ASSERT_LOCATION_SUBMITTED = 'assert_location_submitted',
  DEVICE_TRANSFER_STARTED = 'device_transfer_started',
  DEVICE_TRANSFER_SUBMITTED = 'device_transfer_submitted',
  BLUETOOTH_SCAN_STARTED = 'bluetooth_scan_started',
  BLUETOOTH_SCAN_FINISHED = 'bluetooth_scan_finished',
  BLUETOOTH_CONNECTION_STARTED = 'bluetooth_connection_started',
  BLUETOOTH_CONNECTION_FINISHED = 'bluetooth_connection_finished',
  BLUETOOTH_CONNECTION_FAILED = 'bluetooth_connection_failed',
  WIFI_SCAN_STARTED = 'wifi_scan_started',
  WIFI_SCAN_FINISHED = 'wifi_scan_finished',
  WIFI_CONNECTION_STARTED = 'wifi_connection_started',
  WIFI_CONNECTION_FINISHED = 'wifi_connection_finished',
  WIFI_CONNECTION_FAILED = 'wifi_connection_failed',
}
