name: Main

on:
  push:
    branches: [master, staging, dev]
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, unlocked, auto_merge_enabled]
    branches: [master, staging, dev]

jobs:
  main:
    name: Quality validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js (v16)
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter test
        run: yarn lint
